# Generated by Django 2.2 on 2020-08-16 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200816_0547'),
        ('gallary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_image', to='blog.Blog'),
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallary.Image')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='blog.Comment')),
            ],
            bases=('gallary.image',),
        ),
    ]
