# Generated by Django 2.2 on 2020-08-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200816_1923'),
        ('gallary', '0002_auto_20200816_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallary.Image')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_image', to='blog.Comment')),
            ],
            bases=('gallary.image',),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gallary.Image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='blog.Comment')),
            ],
            bases=('gallary.image',),
        ),
    ]
