# Generated by Django 2.2 on 2020-08-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
